// Create meal
POST http://localhost:3333/meal
Content-Type: application/json

{
  "name":"macarronada",
  "description": "create test",
  "diet": 0
}

###

// Search specific meal
GET http://localhost:3333/meal/3

###

// Search all meals
GET http://localhost:3333/meal

###

// Delete meal
DELETE http://localhost:3333/meal/2

###

// Update Meal
PUT http://localhost:3333/meal/4
Content-Type: application/json

{
  "name": "test update"
}

###

// User Summary
GET http://localhost:3333/meal/summary