// Create User
POST http://localhost:3333/user/signup
Content-Type: application/json

{ 
  "name": "rafael",
  "email": "abc@gmaail.com",
  "password": "12345"
}

###

//Login with cookies
POST http://localhost:3333/user/signin
Content-Type: application/json

{ 
  "email": "abc@gmaail.com",
  "password": "12345"
}

###

// Logout
DELETE http://localhost:3333/user/logout